CREATE TABLE IF NOT EXISTS saju_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL CHECK (slug ~ '^[a-z0-9_-]{4,24}$'),
  name TEXT NOT NULL,
  gender TEXT NOT NULL CHECK (gender IN ('male', 'female')),
  birth_calendar TEXT NOT NULL CHECK (birth_calendar IN ('solar', 'lunar')),
  is_lunar_leap_month BOOLEAN DEFAULT FALSE,
  birth_year INT NOT NULL,
  birth_month INT NOT NULL,
  birth_day INT NOT NULL,
  birth_time_branch TEXT NOT NULL,
  birth_country TEXT NOT NULL,
  timezone TEXT NOT NULL,
  result_json JSONB NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

COMMENT ON COLUMN saju_results.slug IS 'User-entered Life ID used for sharing and exact search.';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'saju_results_slug_life_id_format'
  ) THEN
    ALTER TABLE saju_results
      ADD CONSTRAINT saju_results_slug_life_id_format
      CHECK (slug ~ '^[a-z0-9_-]{4,24}$');
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_saju_results_slug
ON saju_results(slug);

CREATE INDEX IF NOT EXISTS idx_saju_results_deleted_at
ON saju_results(deleted_at);

ALTER TABLE saju_results ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read non-deleted results" ON saju_results;
CREATE POLICY "Public can read non-deleted results"
ON saju_results
FOR SELECT
USING (deleted_at IS NULL);

DROP POLICY IF EXISTS "Public can insert results" ON saju_results;
CREATE POLICY "Public can insert results"
ON saju_results
FOR INSERT
WITH CHECK (deleted_at IS NULL);

CREATE OR REPLACE VIEW public_saju_results
WITH (security_invoker = true)
AS
SELECT
  slug,
  name,
  gender,
  birth_calendar,
  is_lunar_leap_month,
  birth_year,
  birth_month,
  birth_day,
  birth_time_branch,
  birth_country,
  timezone,
  result_json,
  created_at,
  deleted_at
FROM saju_results
WHERE deleted_at IS NULL;

-- No public UPDATE or DELETE policy is created. Soft deletion is handled only
-- by the Supabase Edge Function using the service role key.
--
-- Browser clients can INSERT into the source table, but they read only through
-- public_saju_results, which excludes password_hash.
REVOKE ALL ON saju_results FROM anon, authenticated;
REVOKE ALL ON public_saju_results FROM anon, authenticated;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT (
  slug,
  name,
  gender,
  birth_calendar,
  is_lunar_leap_month,
  birth_year,
  birth_month,
  birth_day,
  birth_time_branch,
  birth_country,
  timezone,
  result_json,
  created_at,
  deleted_at
) ON saju_results TO anon, authenticated;
GRANT INSERT ON saju_results TO anon, authenticated;
GRANT SELECT ON public_saju_results TO anon, authenticated;

GRANT USAGE, SELECT ON SEQUENCE saju_results_id_seq TO anon, authenticated;
